### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by shawalli** [Dobiasd/undictify#1]
I started using this library over the weekend to convert dictionaries (derived from JSON by the requests library) into dataclasses. It was working really well. However, when I pulled in your latest updates, `unpack_dict` and `unpack_json` were more or less gone. It appears as though the entire purpose of the package has shifted into type-checking, instead of unpacking dictionaries and dictionary-like strings (JSON's). Am I missing something here?

**Comment by Dobiasd** [comment]
Hi shawalli,

thanks for the feedback and sorry for the inconvenience.

In version 0.1.x it was:
```python
my_thing = undictify.unpack_json(Thing, json_str)`
```

Now with version 0.2.x it is
```python
my_thing = undictify.type_checked_apply(Thing, **json.loads(json_str))
```
I realized that unpacking JSON is just one specific use-case of a more general problem this library can solve, and I tried to reflect that.

Luckily the change needed on client side (see above) is quite small. And since the library has not yet reached version 1.x, I was hoping such a change would be acceptable. :slightly_smiling_face:

If you still want a function named `unpack_json`, that you can use like `my_thing = unpack_json(Thing, json_str)` (and that has the optional `convert_types` flag), you can create it like this:

```python
TypeT = TypeVar('TypeT')


def unpack_json(target_func: Callable[..., TypeT],
                object_repr: str, convert_types: bool = False) -> TypeT:
    if convert_types:
        return type_checked_apply_skip_convert(target_func,
                                               **json.loads(object_repr))
    return type_checked_apply_skip(target_func,
                                   **json.loads(object_repr))
```

I also [just added it to `examples/readme_examples.py`](https://github.com/Dobiasd/undictify/blob/b587e5457823008d919df233b0f079e24fdc3d14/examples/readme_examples.py#L82-L88).

However I'd like to encourage you to also try the new version, which is adding the `@type_checked_call_skip`  decorator to your target class and unpacking you JSON like this:

```python
my_thing = Thing(**json.loads(json_str))
```

**Comment by shawalli** [comment]
Thanks for the information! I'll give that a try.
