### ISSUE TITLE
Inheritance with @type_checked_constructor()

### ISSUE THREAD

**Issue by gjedlicska** [Dobiasd/undictify#14]
@Dobiasd i really like the idea of your approach, especially the integration with dataclasses, and i works really well for simple cases as far as I tested.

However I'm in a situation, where I'd like to inherit from a base class decorated with type_checked_constructor and also have the same decorator on the derived class to. Right now in version 0.7.1 with python 3.6.8 it raises a TypeError('Class is already wrapped by undictify.')

Also would love to help with the implementation / testing, if that helps.

**Comment by Dobiasd** [comment]
Hi, and thanks for the nice use-case report.

---

Currently, this kind of double wrapping is prohibited to avoid things like the following:

```python3
from typing import NamedTuple

from undictify import type_checked_constructor


@type_checked_constructor(skip=False)
@type_checked_constructor(skip=True)
class Foo:
```

Should it skip or not? Better fail instead of doing something unexpected.

---

Your case probably looks a bit like this:

```python
from typing import NamedTuple

from undictify import type_checked_constructor


@type_checked_constructor()
class Base:
    ...


@type_checked_constructor()
class Derived(Base):
    ...
```

It could happen that by accident you introduce a contradiction by providing different values for the `skip` flag.

Personally, I'm not a big fan of implementation inheritance and would favor composition or interfaces only, but nevertheless, I see why it might be useful for `undictify` to support that case too. :slightly_smiling_face:

---

One solution would be to allow double wrapping, but only for cases where all options (`skip`, `convert` and `converters`) are identical.

So the following in `_unpack.py`

```python3
        if _is_wrapped_func(func):
            raise TypeError('Class is already wrapped by undictify.')
```

would need to be replaced by something less primitive.

If you are interested in giving it a try, I'd be happy to review a pull request that includes not just the change, but also added test coverage for it.

**Comment by gjedlicska** [comment]
Hi! Tanks for the quick response. My use-case is exactly what you wrote. I'll give it a go.

**Comment by gjedlicska** [comment]
I haven't forgotten about the pr, I'm still working on it, when I have the time. I just have a lot on my plate right now...
I'm also working on a PR, where I recreated the testing, packaging, publishing solution with  [Tox](https://tox.readthedocs.io/en/latest/). This is IMHO a more flexible and readable method, than the docker based. @Dobiasd are you interested in such thing?

**Comment by Dobiasd** [comment]
> I haven't forgotten about the pr, I'm still working on it, when I have the time. I just have a lot on my plate right now...

No worries, take your time. :slightly_smiling_face:

> I'm also working on a PR, where I recreated the testing, packaging, publishing solution with Tox. This is IMHO a more flexible and readable method, than the docker based. @Dobiasd are you interested in such thing?

Yes, I am.
@pappasam also [showed interest in re-factoring the automated tests using tox](https://github.com/Dobiasd/undictify/pull/13#issuecomment-548398169). Maybe it makes sense if you two sync on that. :rocket: :rocket:

**Comment by Dobiasd** [comment]
Is this issue still relevant? :slightly_smiling_face:

**Comment by gjedlicska** [comment]
@Dobiasd currently the issue, that was driving this question is sort of in the parking lane, I don't have time to work on this, in the forseeable future (3 mo-s).
You can close it, if you want, if I get around to it, I will open a PR, referencing this issue.
