### ISSUE TITLE
Force conversion independently of type

### ISSUE THREAD

**Issue by richin13** [Dobiasd/undictify#15]
Hello and thanks for this great library! We :heart: it!
Currently I have this use case: I have a JSON like this:

```json
{
	"input": {
		"events": [
			{
				"scheduleId": "U2NoZWR1bGU6MzYwYWY2NTItNmQwOC00YWZmLWEwNDYtOWNmOGQzYTE5ZDE4",
				"type": "...",
				"detail": "..."
			}
		]
	}
}
```

I'm using the following dataclass to deserialize each event object:

```python
@type_checked_constructor(
    converters={
        "schedule_id": _converter_global_id,
        "type": _converter_enum(EventType),
    }
)
@dataclass
class Event:
    schedule_id: str
    type: EnumType
    detail: str
```

My problem is the following: each Event object has a `schedule_id` which is given as BASE-64 string, my converter `_converter_global_id` decodes the Base-64 and returns it but since the input is `str` and output is also `str` the "conversion" is skipped. I believe that decision is taken here: (derived from this conversation https://github.com/Dobiasd/undictify/issues/10#issuecomment-464356127)

https://github.com/Dobiasd/undictify/blob/6dbed39be776c69970583a14c5f06eeabc7d03a7/undictify/_unpack.py#L222

I was wondering if that's something we can override? I tried using the `convert=True` flag with the same outcome :cry:

**Comment by Dobiasd** [comment]
Hi @richin13,

thanks for the nice words.

Your use-case totally makes sense to me. To cover it, we could:

1) Force converter usage in case of `convert==True`: This would be a quick win because the interface parameters would not change. But I feel it could become a pain in the future because the flag is then overloaded with two different meanings, that can no longer be separated.

2) Add an additional flag `force_converter_usage`: Better than version 1, but one use-case would not yet be covered, i.e., one user might want some converters to be only used when needed and some to be always used.

3) Instead of just having a `converters` parameter, have two, i.e., `optional_converters` and `mandatory_converters`: This seems the best solution to me. Updating to the new version would mean one needs to adjust the client code, which is making a decision if one wants the already provided converters to be mandatory or optional. But I think such explicitness might be good.

What do you think?

**Comment by LukeMathWalker** [comment]
Solution 3. sounds good to me :star: To maintain backward compatibility, it would be great to make the already specified converter functions behave as `optional_converters`.

**Comment by richin13** [comment]
I agree with you both on option 3 :rocket: 

I'm not sure about implicitly use `converters` as `optional_converters` (even though they are). I guess it's ok but it's worth adding some sort of warning to let the users know that `converters` option will be removed in a future major version.

**Comment by Dobiasd** [comment]
Since undictify is in version `0.x` instead of `1.x` I'd simply allow the luxury to change the name of a public-facing parameter, i.e., renaming `converters` to `optional_converters`. :grin: I prefer a minor short-term inconvenience over having a confusingly named thing in the API forever with all the long-term inconveniences like more needed explanations (docs) and library code that is harder to understand/maintain/extend.

*But*, after thinking about option 3, I see an issue with it. The following situation might arise:

```python
@type_checked_constructor(
    optional_converters={
        "foo": convert_to_foo_func_a
    },
    mandatory_converters={
        "foo": convert_to_foo_func_b
    }
)
```

This was not possible when we only had one converter dictionary because the keys are unique by definition.

So I'd like to propose a new **option 4** instead:

```python
@type_checked_constructor(
    converters={
        "foo": (convert_to_foo, False) # an optional converter
        "bar": (convert_to_bar, True) # a mandatory converter
    }
)
```

(Or maybe even use an enum instead of a bool.)

Please let me know what you think of it. :slightly_smiling_face:

Yes, it would still be an API-breaking change, because I'd like to avoid allowing non-tuple values (`convert_func`) in the dictionary, that are silently converted to `(convert_func, False)` just for backward compatibility.

**Comment by LukeMathWalker** [comment]
Looks good :+1:

**Comment by Dobiasd** [comment]
Closed with [PR17](https://github.com/Dobiasd/undictify/pull/17).
