### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by LukeMathWalker** [Dobiasd/undictify#5]
@Dobiasd, first of all: great job!

This is something I'd love to use at work and I'd like to contribute to make it production-ready - what is the current status of the library according to your judgement? Where do you need help or contributions?

**Comment by Dobiasd** [comment]
Hi Luca,

thanks for the nice feedback.

In general I would say the library is production-ready. At least it is used in multiple ML microservices in the company I work for. :)

I did not make it version `1.x` yet, because I'm not sure if incompatible changes of the API might be required in the future.

So probably the best thing would be, if you could use the library (if possible) and see if you run into anything (bugs, missing features etc.). Otherwise I'm of course also happy about a code review, additional unit-test cases, improved documentation / examples etc.

Other contributions could include usage reports / blog posts about it and so on.
