### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by LukeMathWalker** [Dobiasd/undictify#6]
I have been playing with the library today and one thing I didn't manage to get up and running were dates: I have a timestamp coming back in JSON response body and I want to get it into a NamedTuple field with type `datetime`; even if `convert=true` I can't manage to get it done - I feel I should be able to specify the function required to the conversion. 

Do you have a way to handle this kind of cases?

**Comment by Dobiasd** [comment]
`str` can not be converted implicitly into `datetime`, one has to call `strptime` or alike. Instead of using a `NamedTuple` I'd probably write a class with an `__init__` function that takes a string and converts to `datetime` in its body. If you run into any problems with this approach, please let me know, ideally with a minimal code example to reproduce the issue.

**Comment by Dobiasd** [comment]
I'll close this issue for now. Feel free to re-open it when needed. :)
